<?xml version="1.0" encoding="utf-8"?><Database Name="Test2" Class="WypozyczalniaDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FELIX-PC\SQLEXPRESS;Initial Catalog=Test2;User ID=sa" SettingsObjectName="Wypozyczalnia.Properties.Settings" SettingsPropertyName="Test2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Część" Member="Częśćs">
    <Type Name="Część">
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cena" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Status_części_Status_części_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Column Name="Statek_Statek_ID" Type="System.Decimal" DbType="Decimal(28,0)" CanBeNull="true" />
      <Column Name="Zamówienie_Zamówienie_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Column Name="Część_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Statek_Część" Member="Statek" ThisKey="Statek_Statek_ID" OtherKey="Statek_ID" Type="Statek" IsForeignKey="true" />
      <Association Name="Status_części_Część" Member="Status_części" ThisKey="Status_części_Status_części_ID" OtherKey="Status_części_ID" Type="Status_części" IsForeignKey="true" />
      <Association Name="Zamówienie_Część" Member="Zamówienie" ThisKey="Zamówienie_Zamówienie_ID" OtherKey="Zamówienie_ID" Type="Zamówienie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Funkcja" Member="Funkcjas">
    <Type Name="Funkcja">
      <Column Name="Nazwa_funkcji" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Funkcja_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Funkcja_Pracownik" Member="Pracowniks" ThisKey="Funkcja_ID" OtherKey="Funkcja_Funkcja_ID" Type="Pracownik" />
    </Type>
  </Table>
  <Table Name="dbo.jest_serwisowany" Member="jest_serwisowanies">
    <Type Name="jest_serwisowany">
      <Column Name="Pracownik_Pracownik_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Statek_Statek_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Pracownik_jest_serwisowany" Member="Pracownik" ThisKey="Pracownik_Pracownik_ID" OtherKey="Pracownik_ID" Type="Pracownik" IsForeignKey="true" />
      <Association Name="Statek_jest_serwisowany" Member="Statek" ThisKey="Statek_Statek_ID" OtherKey="Statek_ID" Type="Statek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Klient" Member="Klients">
    <Type Name="Klient">
      <Column Name="Imię" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nr_dowodu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Klient_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Klient_Rezerwacja" Member="Rezerwacjas" ThisKey="Klient_ID" OtherKey="Klient_Klient_ID" Type="Rezerwacja" />
    </Type>
  </Table>
  <Table Name="dbo.pilotuje" Member="pilotujes">
    <Type Name="pilotuje">
      <Column Name="Pracownik_Pracownik_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rezerwacja_Rezerwacja_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Pracownik_pilotuje" Member="Pracownik" ThisKey="Pracownik_Pracownik_ID" OtherKey="Pracownik_ID" Type="Pracownik" IsForeignKey="true" />
      <Association Name="Rezerwacja_pilotuje" Member="Rezerwacja" ThisKey="Rezerwacja_Rezerwacja_ID" OtherKey="Rezerwacja_ID" Type="Rezerwacja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pracownik" Member="Pracowniks">
    <Type Name="Pracownik">
      <Column Name="Imię" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data_urodzenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Miejsce_urodzenia" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pensja" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Pracownik_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Funkcja_Funkcja_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Association Name="Pracownik_jest_serwisowany" Member="jest_serwisowanies" ThisKey="Pracownik_ID" OtherKey="Pracownik_Pracownik_ID" Type="jest_serwisowany" />
      <Association Name="Pracownik_pilotuje" Member="pilotujes" ThisKey="Pracownik_ID" OtherKey="Pracownik_Pracownik_ID" Type="pilotuje" />
      <Association Name="Funkcja_Pracownik" Member="Funkcja" ThisKey="Funkcja_Funkcja_ID" OtherKey="Funkcja_ID" Type="Funkcja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rezerwacja" Member="Rezerwacjas">
    <Type Name="Rezerwacja">
      <Column Name="Data_wypożyczenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Data_zwrotu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Rezerwacja_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Statek_Statek_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Column Name="Klient_Klient_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Association Name="Rezerwacja_pilotuje" Member="pilotujes" ThisKey="Rezerwacja_ID" OtherKey="Rezerwacja_Rezerwacja_ID" Type="pilotuje" />
      <Association Name="Klient_Rezerwacja" Member="Klient" ThisKey="Klient_Klient_ID" OtherKey="Klient_ID" Type="Klient" IsForeignKey="true" />
      <Association Name="Statek_Rezerwacja" Member="Statek" ThisKey="Statek_Statek_ID" OtherKey="Statek_ID" Type="Statek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Statek" Member="Stateks">
    <Type Name="Statek">
      <Column Name="Silnik" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Rok_produkcji" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cena_za_dobę" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Statek_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Typ_statku_Typ_statku_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL" CanBeNull="false" />
      <Association Name="Statek_Część" Member="Częśćs" ThisKey="Statek_ID" OtherKey="Statek_Statek_ID" Type="Część" />
      <Association Name="Statek_jest_serwisowany" Member="jest_serwisowanies" ThisKey="Statek_ID" OtherKey="Statek_Statek_ID" Type="jest_serwisowany" />
      <Association Name="Statek_Rezerwacja" Member="Rezerwacjas" ThisKey="Statek_ID" OtherKey="Statek_Statek_ID" Type="Rezerwacja" />
      <Association Name="Typ_statku_Statek" Member="Typ_statku" ThisKey="Typ_statku_Typ_statku_ID" OtherKey="Typ_statku_ID" Type="Typ_statku" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status_części" Member="Status_częścis">
    <Type Name="Status_części">
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status_części_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Status_części_Część" Member="Częśćs" ThisKey="Status_części_ID" OtherKey="Status_części_Status_części_ID" Type="Część" />
    </Type>
  </Table>
  <Table Name="dbo.Typ_statku" Member="Typ_statkus">
    <Type Name="Typ_statku">
      <Column Name="Nazwa_typu" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Typ_statku_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Typ_statku_Statek" Member="Stateks" ThisKey="Typ_statku_ID" OtherKey="Typ_statku_Typ_statku_ID" Type="Statek" />
    </Type>
  </Table>
  <Table Name="dbo.Zamówienie" Member="Zamówienies">
    <Type Name="Zamówienie">
      <Column Name="Data_zamówienia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Data_odbioru" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Zamówienie_ID" Type="System.Decimal" DbType="Decimal(28,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Zamówienie_Część" Member="Częśćs" ThisKey="Zamówienie_ID" OtherKey="Zamówienie_Zamówienie_ID" Type="Część" />
    </Type>
  </Table>
</Database>